### ISSUE TITLE
AVG Antivirus is throwing up a threat detection for SlackUI

### ISSUE THREAD

**Issue by faudau** [rfgamaral/SlackUI#7] opened 2015-01-29 13:43 UTC
Just a heads up AVG is finding a threat with one of the components for slackUI. regarding the subprocess CefSharp.

**Comment by MichaelAllenMiller** [comment] 2015-01-30 01:37
Can you submit the offending file to http://www.avg.com/submit-sample ?

**Comment by rfgamaral** [comment] 2015-01-31 15:23
Well, the `CefSharp.BrowserSubprocess.exe` file comes from [cefsharp/CefSharp](https://github.com/cefsharp/CefSharp), there's nothing I can do about it.

**Comment by MichaelAllenMiller** [comment] 2015-01-31 15:37
My guess is they're going to want more info on the false positive. Hopefully @faudau will submit the file to avg for testing, or posting details to https://github.com/cefsharp/CefSharp.

**Comment by rfgamaral** [comment] 2015-01-31 16:45
Let's see what the guys at CefSharp have to say about this :)

**Comment by jornh** [comment] 2015-02-03 20:55
A few things for you guys to look into: https://github.com/cefsharp/CefSharp/issues/779#issuecomment-72328090 ... Oh and BTW thanks for letting us know. :+1: appreciated! Only thing is before we set a lot in motion if going to a newer version resolves it I think it's simply easier to move onwards & upwards. Agree?

**Comment by rfgamaral** [comment] 2015-02-04 11:48
I've been wanting to upgrade to v39 for other reasons but I'd rather hold on that for a while until v39 leaves pre-release status. But first we need to make sure the latest version really fixes this issue.

**Comment by jankurianski** [comment] 2015-02-09 23:35
@faudau [Scanning that file with `virustotal.com`](https://www.virustotal.com/en/file/c0ef23d77c61334d0594024a799105a840bc7b52ee293590ac32747943ec29a0/analysis/) didn't come up with a hit for AVG.  Could you let us know the exact cause of detection from AVG (hopefully it is still in the detection history)?

**Comment by rfgamaral** [comment] 2015-02-18 22:32
It has been 20 days since @faudau reported this issue. Since no one was able to reproduce @faudau's claims and he never reported back, I'm closing this.

**Closed by rfgamaral** 2015-02-18 22:32 UTC

**Comment by BurhanEyimaya** [comment] 2015-05-27 14:57
Hi,

This problem still exists.
I get the same virus warning from AVG.
I attached a screenshot.

Please if you can find the source of this warning I would be very grateful.

Thanks,
Burhan Eyimaya

![virus_warning](https://cloud.githubusercontent.com/assets/7566250/7839150/893d3d2c-0499-11e5-8c16-55ece849b672.png)

**Comment by jankurianski** [comment] 2015-05-28 00:18
@BurhanEyimaya Can you click `[More info]` and take a screenshot of what is shown afterwards?

**Comment by BurhanEyimaya** [comment] 2015-05-28 05:11
When I click [More Info] it opens a web page

http://www.avgthreatlabs.com/ww-en/virus-and-malware-information/info/unknown/?name=Unknown&utm_source=TDPU&utm_medium=IDP&PRTYPE=AVF
